// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Option       = require("./option.js");
var Terrain      = require("./terrain.js");
var DocumentRe   = require("bs-webapi/lib/js/src/dom/nodes/documentRe.js");
var Pervasives   = require("bs-platform/lib/js/pervasives.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var width = window.innerWidth;

var height = window.innerHeight;

var canvas = document.createElement("canvas");

var ctx = canvas.getContext("2d");

Option.map(function (param) {
      param.appendChild(canvas);
      return /* () */0;
    }, Option.andThen(function (prim) {
          return Js_primitive.null_to_opt(prim.body);
        }, DocumentRe.asHtmlDocument(document)));

canvas.setAttribute("height", Pervasives.string_of_int(height));

canvas.setAttribute("width", Pervasives.string_of_int(width));

function drawBackground(context, color, width, height) {
  context.fillStyle = color;
  context.fillRect(0, 0, width, height);
  return /* () */0;
}

drawBackground(ctx, "#000000", width, height);

var terrain = Terrain.create(9);

console.log(terrain);

Terrain.generate(terrain, 0.5);

Terrain.draw(terrain, ctx, width, height);

exports.width          = width;
exports.height         = height;
exports.canvas         = canvas;
exports.ctx            = ctx;
exports.drawBackground = drawBackground;
exports.terrain        = terrain;
/* width Not a pure module */
