// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function create(detail) {
  var size = Math.pow(2, detail) + 1 | 0;
  var max = size - 1 | 0;
  var map = new Float32Array(Caml_array.caml_make_vect(Caml_int32.imul(size, size), 0));
  return /* record */[
          /* size */size,
          /* max */max,
          /* map */map
        ];
}

function get(terrain, x, y) {
  if (x < 0 || x > terrain[/* max */1] || y < 0 || y > terrain[/* max */1]) {
    return -1;
  } else {
    return terrain[/* map */2][x + Caml_int32.imul(terrain[/* size */0], y) | 0];
  }
}

function set(terrain, x, y, v) {
  terrain[/* map */2][x + Caml_int32.imul(terrain[/* size */0], y) | 0] = v;
  return /* () */0;
}

function generate(terrain, roughness) {
  var max = terrain[/* max */1];
  var average = function (values) {
    var valid = values.filter(function (x) {
          return +(x !== -1);
        });
    var total = valid.reduce(function (prim, prim$1) {
          return prim + prim$1;
        }, 0);
    var len = valid.length;
    return total / len;
  };
  var square = function (x, y, size, offset) {
    var avg = average(/* float array */[
          get(terrain, x - size | 0, y - size | 0),
          get(terrain, x + size | 0, y - size | 0),
          get(terrain, x + size | 0, y + size | 0),
          get(terrain, x - size | 0, y + size | 0)
        ]);
    return set(terrain, x, y, avg + offset);
  };
  var diamond = function (x, y, size, offset) {
    var avg = average(/* float array */[
          get(terrain, x, y - size | 0),
          get(terrain, x + size | 0, y),
          get(terrain, x, y + size | 0),
          get(terrain, x - size | 0, y)
        ]);
    return set(terrain, x, y, avg + offset);
  };
  set(terrain, 0, 0, max);
  set(terrain, max, 0, max / 2);
  set(terrain, max, max, 0);
  set(terrain, 0, max, max / 2);
  var _size = max;
  while(true) {
    var size = _size;
    var half = size / 2 | 0;
    var scale = size * roughness;
    if (half < 1) {
      return /* () */0;
    } else {
      var y = half;
      while(y < max) {
        var x = half;
        while(x < max) {
          square(x, y, half, Math.random() * scale * 2 - scale);
          x = x + size | 0;
        };
        y = y + size | 0;
      };
      var y$1 = 0;
      while(y$1 <= max) {
        var x$1 = Caml_int32.mod_(y$1 + half | 0, size);
        while(x$1 <= max) {
          diamond(x$1, y$1, half, Math.random() * scale * 2 - scale);
          x$1 = x$1 + size | 0;
        };
        y$1 = y$1 + half | 0;
      };
      _size = size / 2 | 0;
      continue ;
      
    }
  };
}

function draw(terrain, context, width, height) {
  var waterVal = terrain[/* size */0] * 0.3;
  var max = terrain[/* max */1];
  var size = terrain[/* size */0];
  var rect = function (context, a, b, style) {
    if (b[/* y */1] < a[/* y */1]) {
      return /* () */0;
    } else {
      context.fillStyle = style;
      context.fillRect(a[/* x */0], a[/* y */1], b[/* x */0] - a[/* x */0], b[/* y */1] - a[/* y */1]);
      return /* () */0;
    }
  };
  var brightness = function (x, y, slope) {
    if (y === max || x === max) {
      return "#000";
    } else {
      var b = (slope * 50 | 0) + 128 | 0;
      return "rgba(" + (String(b) + ("," + (String(b) + ("," + (String(b) + ",1)")))));
    }
  };
  var iso = function (x, y) {
    return /* float array */[
            0.5 * ((size + x | 0) - y | 0),
            0.5 * (x + y | 0)
          ];
  };
  var project = function (flatX, flatY, flatZ) {
    var point = iso(flatX, flatY);
    var x0 = width * 0.5;
    var y0 = height * 0.2;
    var z = size * 0.5 - flatZ + point[/* y */1] * 0.75;
    var x = (point[/* x */0] - size * 0.5) * 6;
    var y = (size - point[/* y */1]) * 0.005 + 1;
    return /* float array */[
            x0 + x / y,
            y0 + z / y
          ];
  };
  for(var y = 0 ,y_finish = size - 1 | 0; y <= y_finish; ++y){
    for(var x = 0 ,x_finish = size - 1 | 0; x <= x_finish; ++x){
      var v = get(terrain, x, y);
      var top = project(x, y, v);
      var bottom = project(x + 1 | 0, y, 0);
      var water = project(x, y, waterVal);
      var style = brightness(x, y, get(terrain, x + 1 | 0, y) - v);
      rect(context, top, bottom, style);
      rect(context, water, bottom, "rgba(50, 150, 200, 0.15)");
    }
  }
  return /* () */0;
}

exports.create   = create;
exports.get      = get;
exports.set      = set;
exports.generate = generate;
exports.draw     = draw;
/* No side effect */
